### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by Aulberon** [CerulanLumina/block-of-sky#1]
[crash-2023-04-22_00.16.59-fml.txt](https://github.com/CerulanLumina/block-of-sky/files/11300154/crash-2023-04-22_00.16.59-fml.txt)
[latest.log](https://github.com/CerulanLumina/block-of-sky/files/11300156/latest.log)

**Comment by Aulberon** [comment]
The crash happens on initialization

**Comment by tbvns2** [comment]
I have this too

**Comment by LuminaSapphira** [comment]
Hey, thanks for reporting this. I appreciate it. I'm sorry I've not looked at this for so long - too many interests, not enough time. I'm finally taking a look at this now. I'll release a fix for the current version and see about a 1.20 port as well.

**Comment by LuminaSapphira** [comment]
Fix uploaded to modrinth
And  to curseforge
