### ISSUE TITLE
Crash on Client when joining a server

### ISSUE THREAD

**Issue by LokeYourC3PH** [CerulanLumina/block-of-sky#4]
I am facing the following crash when I try joining a server (on which the mod was just newly installed, so there's no placed block yet):
[crash-2023-08-30_20.30.48-client.txt](https://github.com/CerulanLumina/block-of-sky/files/12475101/crash-2023-08-30_20.30.48-client.txt)

**Comment by LuminaSapphira** [comment]
Seems like its probably an incompatibility with Iris. Does it still happen without it?

I'll see what I can do to fix compat so people can have shaders and blocks of sky :)
